version: "3.8"

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    ports:
      - 3000:3000
      - 9222:9222
    expose:
      - 3000
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start
