import { useGetPokemonQuery } from "./HelloWorld.gql"
import { HelloWorldComponent } from "./HelloWorld.types"

import "./HelloWorld.scss"

/**
 * This is an example component that uses the useGetPokemonQuery hook generated by graphql-codegen from the
 * https://pokeapi.co/ GraphQL API.
 */
const HelloWorld: HelloWorldComponent = () => {
  const { data } = useGetPokemonQuery()
  return (
    <div className='hello-world'>
      {data?.pokemon?.map(
        pokemon =>
          pokemon?.info?.name &&
          (pokemon.sprites as { front_default?: string })?.front_default && (
            <div key={pokemon?.info?.id} className='pokemon'>
              {(pokemon.sprites as { front_default?: string })?.front_default && (
                <img src={(pokemon.sprites as { front_default?: string })?.front_default} alt={pokemon.info.name} />
              )}
              <p>{pokemon.info.name}</p>
            </div>
          ),
      )}
    </div>
  )
}

export default HelloWorld
