# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'main' && 'production' || 'development'}}
    env:
      VITE_API_URL: ${{  secrets.VITE_API_URL }}
    strategy:
      matrix:
        node-version: [21.1.0]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: generate GraphQL files
        run: npm run codegen
      - name: Build app
        run: npm run build --if-present
      - name: Run tests
        run: npm run test:coverage
      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
